---
- name: Update apt cache
  sudo: yes
  apt: update_cache=yes

- name: Install required packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - openssh-server
    - postfix

- name: Get gitlab package
  get_url: url=https://downloads-packages.s3.amazonaws.com/ubuntu-14.04/gitlab-ce_7.10.0~omnibus.2-1_amd64.deb dest=/tmp/gitlab.deb

- name: Install downloaded Gitlab package
  apt: deb=/tmp/gitlab.deb

- name: Copy GitLab configuration file
  template: src=gitlab.rb.j2 dest=/etc/gitlab/gitlab.rb owner=root group=root mode=600
  notify: Restart gitlab

- name: Get the Gitlab runner package
  get_url: url=https://s3-eu-west-1.amazonaws.com/downloads-packages/ubuntu-14.04/gitlab-runner_5.2.0~omnibus.1-1_amd64.deb dest=/tmp/gitlab_runner.deb

- name: Install downloaded Gitlab runner package
  apt: deb=/tmp/gitlab_runner.deb

- name: Add Gitlab runner user
  sudo: yes
  command: useradd -s /bin/false -m -r gitlab-runner

- name: Add Gitlab runner Upstart script
  sudo: yes
  command: cp /opt/gitlab-runner/doc/install/upstart/gitlab-runner.conf /etc/init/

- name: Stop Gitlab runner for now
  sudo: yes
  service: name=gitlab-runner enabled=yes state=stopped